# .github/workflows/python-tests.yml
name: Python Tests

on:
  # feature/XXX のブランチに push があったとき
  push:
    branches:
      - 'feature/*'
  # feature/XXX から main への PR を作成・更新したとき
  pull_request:
    branches:
      - 'feature/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas openpyxl

      - name: Run pytest
        run: |
          pytest -q
